linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused
  disable:
    - gci
    - tagliatelle
    - wsl
    - exhaustruct
    - lll
    - varnamelen
    - nlreturn
    - err113
    - wrapcheck
    - testpackage
    - nolintlint
    - depguard
    - ireturn
    - perfsprint
    - musttag
    - tagalign
    - mnd
    - canonicalheader
    - intrange
    - testifylint
    - paralleltest
    - nonamedreturns
    - dupword
    - gochecknoglobals
    - gosmopolitan
    - forbidigo
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocognit
          - nestif
          - cyclop
          - funlen
      - path: examples/
        linters:
          - goheader
linters-settings:
  cyclop:
    max-complexity: 12
  funlen:
    lines: 90
  errcheck:
    # errcheck -verbose .
    exclude-functions:
      - (github.com/nats-io/nats.go/micro.Service).Stop
      - (github.com/nats-io/nats.go/micro.Group).AddEndpoint
      - (github.com/nats-io/nats.go/micro.Request).Respond
      - (github.com/nats-io/nats.go/micro.Request).RespondJSON
      - (github.com/nats-io/nats.go/micro.Request).Error
      - (*github.com/nats-io/nats.go.Subscription).Unsubscribe
  goheader:
    values:
      regexp:
        fromyear: \d\d\d\d
    template: |-
      SPDX-FileCopyrightText: {{ FROMYEAR }} Masa Cento
      SPDX-License-Identifier: MPL-2.0

