version: 2

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/jumonmd/jumon/internal/version.Version=v{{.Version}}

archives:
  - name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    wrap_in_directory: true
    format: zip
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
