name: release

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: Release
        uses: goreleaser/goreleaser-action@v6.3.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
