name: test

on:
  push:
    branches: ["main", "develop", "feature/**"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: latest
          args: --timeout=2m

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
